FROM graylog/graylog:2.4.6-1

# Copy your init script into the container
COPY docker-testing/graylog_init.sh /scripts/graylog_init.sh

# Make sure it's executable
RUN chmod +x /scripts/graylog_init.sh

# Use your script as entrypoint
ENTRYPOINT ["/scripts/graylog_init.sh"]
